<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ai_player</name>
  <version>0.0.0</version>
  <description>Adversário controlado por IA, com dificuldades ajustáveis</description>
  <maintainer email="fernando.murusaki@unesp.br">Carrossel Caipira</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>shared_interfaces</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
