<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>vision_game</name>
  <version>0.0.0</version>
  <description>Visão do campo: câmera para /game_data</description>
  <maintainer email="fernando.murusaki@unesp.br">Carrossel Caipira</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>shared_interfaces</depend>
  <depend>python3-opencv</depend>
  <depend>python3-numpy</depend>
  <depend>python3-aiohttp</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
